// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {time} from '../models';
import {models} from '../models';
import {api} from '../models';

export function ClearHistory():Promise<void>;

export function DeleteHistory(arg1:time.Time):Promise<void>;

export function DeleteMock(arg1:any):Promise<void>;

export function DeleteRequest(arg1:any):Promise<void>;

export function DuplicateFolder(arg1:any):Promise<void>;

export function DuplicateRequest(arg1:any):Promise<models.RequestInfo>;

export function ExportPostman(arg1:string):Promise<void>;

export function FuzzRequest(arg1:any):Promise<Array<api.FuzzResult>>;

export function GetActiveEnv():Promise<Record<string, string>>;

export function GetEnvironments():Promise<Array<models.Environment>>;

export function GetHistory():Promise<Array<models.HistoryRecord>>;

export function GetMockStats():Promise<Record<string, models.MockStat>>;

export function GetProxyStatus():Promise<any>;

export function GetRequests():Promise<Record<string, any>>;

export function GetVariables():Promise<Record<string, string>>;

export function GetVaultStatus():Promise<Record<string, boolean>>;

export function GetWorkflows():Promise<Array<models.Workflow>>;

export function GraphQLIntrospection(arg1:any):Promise<Record<string, any>>;

export function HammerRequest(arg1:any):Promise<api.HammerResults>;

export function ImportCurl(arg1:string):Promise<models.RequestInfo>;

export function ImportOpenAPI(arg1:any):Promise<any>;

export function ImportPostman(arg1:any):Promise<any>;

export function NewRequest(arg1:any):Promise<models.RequestInfo>;

export function RenameFolder(arg1:any):Promise<void>;

export function ReorderRequests(arg1:any):Promise<void>;

export function RunRunner(arg1:any):Promise<Array<api.RunnerResult>>;

export function RunWorkflow(arg1:models.Workflow):Promise<Array<api.WorkflowLog>>;

export function SQLRequest(arg1:any):Promise<Record<string, any>>;

export function SaveEnvironments(arg1:Array<models.Environment>):Promise<void>;

export function SaveMockResponse(arg1:any):Promise<void>;

export function SaveSchema(arg1:any):Promise<void>;

export function SaveVariables(arg1:Record<string, string>):Promise<void>;

export function SaveWorkflows(arg1:Array<models.Workflow>):Promise<void>;

export function SendRequest(arg1:any):Promise<Record<string, any>>;

export function SetActiveEnv(arg1:any):Promise<void>;

export function StartProxy(arg1:any):Promise<void>;

export function StopProxy():Promise<void>;

export function UnlockVault(arg1:any):Promise<void>;

export function UpdateRequest(arg1:any):Promise<models.RequestInfo>;

export function VaultEncrypt(arg1:any):Promise<any>;

export function WSClose():Promise<void>;

export function WSConnect(arg1:any):Promise<void>;

export function WSGetMessages():Promise<Array<api.WSMessage>>;

export function WSSend(arg1:any):Promise<void>;
